export default [
  {
    id: 'pose-anything-anywhere',
    title: 'Pose Anything Anywhere: Model-free Object Poses from Arbitrary References',
    venue: 'European Conference on Computer Vision (ECCV)', year: 2026, area: 'perception',
    media: { src: '/assets/publications/pany-teaser.webp', width: 1418, height: 520, alt: 'PANY paper teaser: arbitrary references, 6D poses, and object-centric geometry' },
    authors: [
      { name: 'Hongli Xu', equal: true }, { name: 'Jiaqi Hu', equal: true }, { name: 'Junwen Huang', equal: true },
      { name: 'Boyang Zhong', featured: true }, { name: 'Peter K. T. Yu' }, { name: 'Nassir Navab' },
      { name: 'Benjamin Busam' }, { name: 'Slobodan Ilic' }
    ],
    summary: 'PANY estimates the 6D pose of unseen objects from one or sparse arbitrary RGB or RGB-D references. Its multi-view geometry backbone and pose-graph registration aggregate unposed assist views to improve robustness under occlusion and wide viewpoint changes.',
    links: [{ type: 'arxiv', url: 'https://arxiv.org/abs/2606.23634', label: 'Read the PANY preprint', external: true }, { type: 'project', url: 'https://demianhj.github.io/PANY/', label: 'Visit the PANY project website', external: true }]
  },
  {
    id: 'funcanon',
    title: 'FUNCanon: Learning Pose-Aware Action Primitives via Functional Object Canonicalization for Generalizable Robotic Manipulation',
    venue: 'IEEE International Conference on Robotics and Automation (ICRA)', year: 2026, area: 'embodied',
    media: { src: '/assets/publications/funcanon-teaser.webp', width: 1323, height: 662, alt: 'FUNCanon paper teaser: functional alignment, action primitives, and sim-to-real manipulation' },
    authors: [
      { name: 'Hongli Xu', equal: true }, { name: 'Lei Zhang', equal: true }, { name: 'Xiaoyue Hu', equal: true },
      { name: 'Boyang Zhong', featured: true }, { name: 'Kaixin Bai' }, { name: 'Zoltán-Csaba Márton' },
      { name: 'Zhenshan Bing' }, { name: 'Zhaopeng Chen' }, { name: 'Alois Christian Knoll' }, { name: 'Jianwei Zhang' }
    ],
    summary: 'FUNCanon decomposes long-horizon manipulation into actor–verb–object action chunks. Affordance-guided functional canonicalization aligns objects into shared functional frames, allowing pose-aware action primitives to transfer across object categories and tasks.',
    links: [
      { type: 'arxiv', url: 'https://arxiv.org/abs/2509.19102', label: 'Read the preprint', external: true },
      { type: 'project', url: 'https://sites.google.com/view/funcanon', label: 'Visit the project website', external: true }
    ]
  },
  {
    id: 'vbvr',
    title: 'A Very Big Video Reasoning Suite',
    venue: 'International Conference on Machine Learning (ICML)', year: 2026, area: 'generation',
    media: { src: '/assets/publications/vbvr-teaser.webp', width: 1117, height: 700, alt: 'VBVR paper teaser: video reasoning tasks and evaluation results' },
    authors: [
      { name: 'Maijunxian Wang' },
      { name: 'Ruisi Wang' },
      { name: 'Juyi Lin' },
      { name: 'Ran Ji' },
      { name: 'Thaddäus Wiedemer' },
      { name: 'Qingying Gao' },
      { name: 'Dezhi Luo' },
      { name: 'Yaoyao Qian' },
      { name: 'Lianyu Huang' },
      { name: 'Zelong Hong' },
      { name: 'Jiahui Ge' },
      { name: 'Qianli Ma' },
      { name: 'Hang He' },
      { name: 'Yifan Zhou' },
      { name: 'Lingzi Guo' },
      { name: 'Lantao Mei' },
      { name: 'Jiachen Li' },
      { name: 'Hanwen Xing' },
      { name: 'Tianqi Zhao' },
      { name: 'Yu Fengyuan' },
      { name: 'Weihang Xiao' },
      { name: 'Yizheng Jiao' },
      { name: 'Jianheng Hou' },
      { name: 'Danyang Zhang' },
      { name: 'Pengcheng Xu' },
      { name: 'Boyang Zhong', featured: true },
      { name: 'Zehong Zhao' },
      { name: 'Gaoyun Fang' },
      { name: 'John Kitaoka' },
      { name: 'Xu Yile' },
      { name: 'Hua Xu' },
      { name: 'Kenton Blacutt' },
      { name: 'Tin Nguyen' },
      { name: 'Siyuan Song' },
      { name: 'Haoran Sun' },
      { name: 'Shaoyue Wen' },
      { name: 'Linyang He' },
      { name: 'Runming Wang' },
      { name: 'Yanzhi Wang' },
      { name: 'Mengyue Yang' },
      { name: 'Ziqiao Ma' },
      { name: 'Raphaël Millière' },
      { name: 'Freda Shi' },
      { name: 'Nuno Vasconcelos' },
      { name: 'Daniel Khashabi' },
      { name: 'Alan Yuille' },
      { name: 'Yilun Du' },
      { name: 'Ziming Liu' },
      { name: 'Dahua Lin' },
      { name: 'Ziwei Liu' },
      { name: 'Vikash Kumar' },
      { name: 'Yijiang Li' },
      { name: 'Lei Yang' },
      { name: 'Zhongang Cai' },
      { name: 'Hokin Deng' }
    ],
    shortAuthors: 'Maijunxian Wang, Ruisi Wang, Juyi Lin, …, <strong><u>Boyang Zhong</u></strong>, et al.',
    summary: 'VBVR introduces a large-scale video reasoning suite with 200 curated tasks and over one million clips. Its rule-based, human-aligned benchmark provides verifiable evaluation of temporal, spatial, and causal reasoning in video models.',
    links: [
      { type: 'paper', url: 'https://proceedings.mlr.press/v306/wang26ia.html', label: 'Read the ICML paper', external: true },
      { type: 'arxiv', url: 'https://arxiv.org/abs/2602.20159', label: 'Read the VBVR preprint', external: true },
      { type: 'project', url: 'https://video-reason.com/?v=vbvr', label: 'Visit the VBVR project', external: true }
    ]
  }
];
